File: Malekula.xml seed: 1689949435971 threads: 4
Loading package Babel v0.4.1 BEAST.base v2.7.3 SA v2.1.0 starbeast3 v1.1.6 BDSKY v1.5.0 innovations v0.0.1 BEAST.app v2.7.3 feast v9.4.0 BEASTLabs v2.0.0 ORC v1.1.1    
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 2 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 2 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 2 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 2 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 2 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 2 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 2 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 2 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 2 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 3 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 3 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 3 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 3 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 3 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 3 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 2 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 3 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 3 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 4 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 4 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 4 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 4 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 4 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 4 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 4 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 4 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 4 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 4 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 5 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 4 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 5 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 5 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 3 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 5 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 5 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 5 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 5 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 5 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 5 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 5 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 5 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 6 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 6 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 6 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 5 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 5 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 6 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 7 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 7 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 7 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 7 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 7 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 7 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 7 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 7 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 7 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 6 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 7 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 7 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 8 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 8 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 8 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 8 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 8 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 8 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 8 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 8 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 7 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 8 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 8 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 8 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 8 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 8 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 7 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 8 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 8 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 9 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 9 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 9 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 9 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 9 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 9 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 9 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 9 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 9 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 9 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 9 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 9 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 9 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 10 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 10 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 10 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 10 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 10 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 10 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 10 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 10 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 10 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 10 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 10 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 10 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 10 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 10 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 11 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 11 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 11 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 11 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 11 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 11 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 11 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 11 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 11 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 11 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 11 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 11 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 11 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 11 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 11 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 12 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 12 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 11 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 12 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 12 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 12 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 12 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 12 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 12 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 12 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 13 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 13 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 12 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 12 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 13 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 13 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 11 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 13 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 12 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 13 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 13 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 13 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 13 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 14 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 14 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 13 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 14 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 14 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 14 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 14 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 14 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 14 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 14 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 14 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 14 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 14 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 15 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 14 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 15 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 15 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 14 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 15 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 15 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 14 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 14 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 15 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 13 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 16 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 16 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 16 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 16 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 16 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 17 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 17 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 17 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 17 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 18 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 18 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 17 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 18 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 19 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 19 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 19 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 19 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 19 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 18 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 19 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 20 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 21 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 22 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 23 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 23 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 23 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 24 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 24 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 24 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 25 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 25 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 25 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 24 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 26 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 26 unique site patterns.
  Using rescaling scheme : dynamic
  Using ambiguities in tree likelihood.
  Ignoring character uncertainty in tree likelihood.
  With 28 unique site patterns.
  Using rescaling scheme : dynamic
Writing file Malekula.log
Writing file Malekula.trees
Writing file site_likelihoods.txt
